### PR TITLE
Bugfix/whitelist-synchronisation

### PR DESCRIPTION
**Pull request by OliverNeff**
## Description:
Syncronize users by adding and deleting whitelist users.
Users are now added  to cours if a whitelist user is created or delete from course if delete a whitelist user.

## Known Issues:
Review from 2018-01-18
see #501 
------
_Remember to prefix your PR-Title with `⚠ WIP: ` if you still work on it.
If you have reached a final state, remove the prefix._

### CODE REVIEW

**Comment by OliverNeff** [comment]
Sorry I deleted the comment from coveralls: 
Coverage increased (+0.5%) to 62.802%

**Comment by PatrickSkowronek** [comment]
I looked at the code, which is good. But I did not understand the logic behind the description of this pr. I can still add multiple times the same student to a whitelist. Another problem is uploading a csv file, which is like the test resource example. The first name and second name is switch:
screenshot from 2018-01-23 00-06-36

As a Student in the whitelist I cloud not enter a course. I did not see it either. Should that not be possible?

**Comment by OliverNeff** [comment]
@PatrickSkowronek Have you updated your fixtures bevore you test it? 
This commit should prevent duplicates: 
https://github.com/h-da/geli/pull/493/commits/35af85610dcd97470c29780da9d14660009cdde2

see also stackoverflow: 
https://stackoverflow.com/questions/14692726/unique-constraint-with-two-fields-in-mongodb

**Comment by PatrickSkowronek** [comment]
@OliverNeff I did updated the fixtures. But still the csv input is broken or saves the data wrong. I cloud add a Student which was already whitelisted with the csv file. In this case it did not work proper. I think this should be checked in the front and backend.

**Comment by OliverNeff** [comment]
Then I look after it this evening again. You should enter the course when are whitelistet for it. This was implemented last semester.

**Comment by OliverNeff** [comment]
Close because of #501

**Pull request closed without merging**
