### PR TITLE
Update project dependencies

### LINKED ISSUE #121: Update to Node 8
# User Story

### As a: 
developer

### I want:
to update to Node v8

### so that:
we can use npm 5.0 (see #115) and are using a LTS supported till december 2019

## Acceptance criteria:
- [x] project uses node 8
- [x] travis uses node 8
- [ ] vagrant uses node 8
- docker uses node 8
  - [x] dev
  - [x] docker-hub
- [x] Update all Dependencies, but at least:
  - tslint (api and fe to the same version)
  - npm

## Additional info:
https://github.com/nodejs/LTS#lts-schedule1

### PR DESCRIPTION
**Pull request by grosspersky**
## Description:
This PR updates alll project dependencies in the backend and the frontend.

Closes #121 

## Improvements
Usage auf newest available versions of dependencies.
Includes usage of:
* Node 8
* NPM 5
* Angular 4.4.5

## Known Issues:
* Angular currently is only supporting typescript below version 2.4.0, so the frontend has an older version of typescript as the backend
* TSLint generates a warning: ``Warning: The 'no-use-before-declare' rule requires type information.`` This doesn't prevent compilation in any way.
* FixtureLoader generates a warning: (node:10000) DeprecationWarning: Implicit async custom validators (custom validators that take 2 arguments) are deprecated in mongoose >= 4.9.0. See http://mongoosejs.com/docs/validation.html#async-custom-validators for more info.

### CODE REVIEW

**Comment by grosspersky** [comment]
Test for creating new code katas produces the following error:
{ name: 'TypeError',
  message: 'Cannot read property \'toString\' of undefined',
  stack: 'TypeError: Cannot read property \'toString\' of undefined\n    at transform (D:\\Git\\geli\\api\\build\\src\\models\\units\\Unit.js:30:38)\n    at model.Document.$toObject (D:\\Git\\geli\\api\\node_modules\\mongoose\\lib\\document.js:2081:19)\n    at model.Document.toObject (D:\\Git\\geli\\api\\node_modules\\mongoose\\lib\\document.js:2208:1
5)\n    at clone (D:\\Git\\geli\\api\\node_modules\\mongoose\\lib\\utils.js:254:16)\n    at cloneArray (D:\\Git\\geli\\api\\node_modules\\mongoose\\lib\\utils.js:362:14)\n    at clone (D:\\Git\\geli\\api\\node_modules\\mongoose\\lib\\utils.js:247:12)\n    at cloneObject (D:\\Git\\geli\\api\\node_modules\\mongoose\\lib\\utils.js:343:13)\n    at clone (
D:\\Git\\geli\\api\\node_modules\\mongoose\\lib\\utils.js:260:16)\n    at model.Document.$toObject (D:\\Git\\geli\\api\\node_modules\\mongoose\\lib\\document.js:2043:13)\n    at model.Document.toObject (D:\\Git\\geli\\api\\node_modules\\mongoose\\lib\\document.js:2208:15)\n    at Lecture_1.Lecture.findById.then.then (D:\\Git\\geli\\api\\build\\src\\co
ntrollers\\UnitController.js:34:40)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)' }

**Comment by khase** [comment]
To me it does not make any sense for the Unit to contain a reference to the Course since it is a child of a lecture which is itself a child of a course ??

**Comment by grosspersky** [comment]
The reference significantly reduces complexity when aggregation unit data for various reports. Without it you would have to join across five collections (course, lecture, unit, user, progress) and aggregate your units manually if you want to get all units of a course to be presented for the teacher report. 

But in case of the teacher report the course and lecture data is irrelevant. With the attribute you can skip the course and lecture collection entirely and just use the unit, user and progress collection to display all relevant information.

This stays the same for the student report were you just need to query all units of the corresponding student and group them by course, which can be done without the course collection with this attribute.

**Comment by aeimer** [comment]
At first sight it looks good. But we HAVE to wait to merge this code... First we need to polish our running code.

**Pull request merged**
