### PR TITLE
Feature/441 api doc content

### LINKED ISSUE #441: Introduce API-Docu, build automatically
# User Story

### As a: 
Developer

### I want:
to have an API-Documentation

### so that:
I can see all URL-Paths and their functions.

## Acceptance criteria:
- [x] All API-Functions are commented
- [x] Build the Documentation on build time
- [x] The documentation should be generated only on tagged builds
- [x] Publish the build (as GH Pages)
- [x] The version of the docu should be switched

## Additional info:
https://pages.github.com/

------
_Please tag this issue if you are sure to which tag(s) it belongs._

### PR DESCRIPTION
**Pull request by micpah**
## Description:
Provides the code comments for API functions which will be used to generate the API documentation  (see #499).

Closes #441

## Improvements
- API functions have comments (formatted for apiDoc)

## Known Issues:
_NONE_

------
_Remember to prefix your PR-Title with `⚠ WIP: ` if you still work on it.
If you have reached a final state, remove the prefix._

### CODE REVIEW

**Comment by aeimer** [comment]
@micpah How is your progress? 

If you are finished, @lukaskorte could review the comments?!

**Comment by aeimer** [comment]
@micpah please resolve the conlfict so I can merge this

**Comment by micpah** [comment]
@aeimer @lukaskorte I'm still adding comments for the api controllers. There are a few left. I'm currently on it and will need a couple of hours. I'll resolve the conflict.

**Comment by aeimer** [comment]
Perfect 👍

**Comment by micpah** [comment]
@aeimer @lukaskorte Done.

**Comment by aeimer** [comment]
@micpah could you add a link to the README, so people can find the API-Docs more easy

**Pull request merged**
