### PR TITLE
Feature/test whitelist

### PR DESCRIPTION
**Pull request by OliverNeff**
## Description:
Merged Branch of Merge Request #489 #493 and #494 for testing and bug fixing.

## Known Issues:
Review at 2018-01-18

------
_Remember to prefix your PR-Title with `⚠ WIP: ` if you still work on it.
If you have reached a final state, remove the prefix._

### CODE REVIEW

**Comment by OliverNeff** [comment]
* Fix visible of whitelist courses.
* Leave course has some porblems it works sometimes.

**Comment by OliverNeff** [comment]
Leave course is a problem which is also on develop whithout whitelistet courses.

**Comment by PatrickSkowronek** [comment]
Sofar it is working fine!
The only thing that encounter me while testing was #511 .

**Comment by OliverNeff** [comment]
Add some optimization: 
* The method searchUsers return now an concrete interface type.
* Limit is now an optional parameter by searching.

**Pull request merged**
