### PR TITLE
Bugfixes mat fab btn on edit course content

### PR DESCRIPTION
**Pull request by aeimer**
## Description:
Makes the mat fab btn have more space on course edit.

------
_Remember to prefix your PR-Title with `⚠ WIP: ` if you still work on it.
If you have reached a final state, remove the prefix._

### CODE REVIEW

**Comment by aeimer** [comment]
@felixbrucker please check if this bug needs to be fixed or if it disappeared with your new course edit routing. 

Please give feedback to this pr :)

**Comment by felixbrucker** [comment]
The new routing will not change this, so you are encouraged to merge this

**Comment by lukaskorte** [comment]
This kind of "spacer" div is not good style. This looks like it can be solved using pure CSS.

Also the PR does not clearly state the issue that it is trying to solve.

**Comment by aeimer** [comment]
There was no issue, @grosspersky handed the issue to me.

The Problem here was that the tab-content has overflow hidden. And even with a high z-index I was not able to move the button further to the bottom. So I had to add that spacer div. I know it is hacky, but it works...

**Pull request closed without merging**
